config/routes.rb
Folha::Application.routes.draw do
  resources :vinculos

  resources :cargos

  resources :funcionarios

   root 'paginas#index'

end

app/models/cargo.rb
class Cargo < ActiveRecord::Base
    
end

app/models/funcionario.rb
class Funcionario < ActiveRecord::Base
end

app/models/vinculo.rb
class Vinculo < ActiveRecord::Base
    belongs_to :funcionario
    validates :funcionario, presence: true
    
    belongs_to :cargo
    validates :cargo, presence: true
    
    validates :matricula, numericality: { greater_than: 0 }, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cargos_controller.rb
class CargosController < ApplicationController
  before_action :set_cargo, only: [:show, :edit, :update, :destroy]

  # GET /cargos
  # GET /cargos.json
  def index
    @cargos = Cargo.all
  end

  # GET /cargos/1
  # GET /cargos/1.json
  def show
  end

  # GET /cargos/new
  def new
    @cargo = Cargo.new
  end

  # GET /cargos/1/edit
  def edit
  end

  # POST /cargos
  # POST /cargos.json
  def create
    @cargo = Cargo.new(cargo_params)

    respond_to do |format|
      if @cargo.save
        format.html { redirect_to @cargo, notice: 'Cargo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cargo }
      else
        format.html { render action: 'new' }
        format.json { render json: @cargo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cargos/1
  # PATCH/PUT /cargos/1.json
  def update
    respond_to do |format|
      if @cargo.update(cargo_params)
        format.html { redirect_to @cargo, notice: 'Cargo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cargo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cargos/1
  # DELETE /cargos/1.json
  def destroy
    @cargo.destroy
    respond_to do |format|
      format.html { redirect_to cargos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cargo
      @cargo = Cargo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cargo_params
      params.require(:cargo).permit(:codigo, :descricao, :salario)
    end
end

app/controllers/funcionarios_controller.rb
class FuncionariosController < ApplicationController
  before_action :set_funcionario, only: [:show, :edit, :update, :destroy]

  # GET /funcionarios
  # GET /funcionarios.json
  def index
    if params[:q_cpf].blank?
        @funcionarios = Funcionario.all
    else
        @funcionarios = Funcionario.where cpf: params[:q_cpf]
    end  
  end

  # GET /funcionarios/1
  # GET /funcionarios/1.json
  def show
  end

  # GET /funcionarios/new
  def new
    @funcionario = Funcionario.new
  end

  # GET /funcionarios/1/edit
  def edit
  end

  # POST /funcionarios
  # POST /funcionarios.json
  def create
    @funcionario = Funcionario.new(funcionario_params)

    respond_to do |format|
      if @funcionario.save
        format.html { redirect_to @funcionario, notice: 'Funcionario was successfully created.' }
        format.json { render action: 'show', status: :created, location: @funcionario }
      else
        format.html { render action: 'new' }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funcionarios/1
  # PATCH/PUT /funcionarios/1.json
  def update
    respond_to do |format|
      if @funcionario.update(funcionario_params)
        format.html { redirect_to @funcionario, notice: 'Funcionario was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funcionarios/1
  # DELETE /funcionarios/1.json
  def destroy
    @funcionario.destroy
    respond_to do |format|
      format.html { redirect_to funcionarios_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funcionario
      @funcionario = Funcionario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def funcionario_params
      params.require(:funcionario).permit(:nome, :cpf)
    end
end

app/controllers/paginas_controller.rb
class PaginasController < ApplicationController
    
    def index
    
    
    end
    
end

app/controllers/vinculos_controller.rb
class VinculosController < ApplicationController
  before_action :set_vinculo, only: [:show, :edit, :update, :destroy]

  # GET /vinculos
  # GET /vinculos.json
  def index
    @vinculos = Vinculo.all
  end

  # GET /vinculos/1
  # GET /vinculos/1.json
  def show
  end

  # GET /vinculos/new
  def new
    @vinculo = Vinculo.new
  end

  # GET /vinculos/1/edit
  def edit
  end

  # POST /vinculos
  # POST /vinculos.json
  def create
    @vinculo = Vinculo.new(vinculo_params)

    respond_to do |format|
      if @vinculo.save
        format.html { redirect_to @vinculo, notice: 'Vinculo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @vinculo }
      else
        format.html { render action: 'new' }
        format.json { render json: @vinculo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vinculos/1
  # PATCH/PUT /vinculos/1.json
  def update
    respond_to do |format|
      if @vinculo.update(vinculo_params)
        format.html { redirect_to @vinculo, notice: 'Vinculo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @vinculo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vinculos/1
  # DELETE /vinculos/1.json
  def destroy
    @vinculo.destroy
    respond_to do |format|
      format.html { redirect_to vinculos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vinculo
      @vinculo = Vinculo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vinculo_params
      params.require(:vinculo).permit(:matricula, :dt_admissao, :cargo_id, :funcionario_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cargos_helper.rb
module CargosHelper
end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/helpers/vinculos_helper.rb
module VinculosHelper
end

app/views/cargos/_form.html.erb
<%= form_for(@cargo) do |f| %>
  <% if @cargo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cargo.errors.count, "error") %> prohibited this cargo from being saved:</h2>

      <ul>
      <% @cargo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :codigo %><br>
    <%= f.number_field :codigo %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br>
    <%= f.text_field :descricao %>
  </div>
  <div class="field">
    <%= f.label :salario %><br>
    <%= f.text_field :salario %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cargos/edit.html.erb
<h1>Editing cargo</h1>

<%= render 'form' %>

<%= link_to 'Show', @cargo %> |
<%= link_to 'Back', cargos_path %>

app/views/cargos/index.html.erb
<h1>Listing cargos</h1>

<table class="table">
  <thead>
    <tr>
      <th>Codigo</th>
      <th>Descricao</th>
      <th>Salario</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cargos.each do |cargo| %>
      <tr>
        <td><%= cargo.codigo %></td>
        <td><%= cargo.descricao %></td>
        <td><%= cargo.salario %></td>
        <td><%= link_to 'Show', cargo %></td>
        <td><%= link_to 'Edit', edit_cargo_path(cargo) %></td>
        <td><%= link_to 'Destroy', cargo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          
      </tr>
    <% end %>
  </tbody>
</table>




<%= link_to 'New Cargo', new_cargo_path %> 
<%= link_to "Pagina inicial", root_url %>

app/views/cargos/new.html.erb
<h1>New cargo</h1>

<%= render 'form' %>

<%= link_to 'Back', cargos_path %>

app/views/cargos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Codigo:</strong>
  <%= @cargo.codigo %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @cargo.descricao %>
</p>

<p>
  <strong>Salario:</strong>
  <%= @cargo.salario %>
</p>

<%= link_to 'Edit', edit_cargo_path(@cargo) %> |
<%= link_to 'Back', cargos_path %>

app/views/funcionarios/_form.html.erb
<%= form_for(@funcionario) do |f| %>
  <% if @funcionario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@funcionario.errors.count, "error") %> prohibited this funcionario from being saved:</h2>

      <ul>
      <% @funcionario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :cpf %><br>
    <%= f.text_field :cpf %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/funcionarios/edit.html.erb
<h1>Editing funcionario</h1>

<%= render 'form' %>

<%= link_to 'Show', @funcionario %> |
<%= link_to 'Back', funcionarios_path %>

app/views/funcionarios/index.html.erb
<h1>Listagem de Funcionarios</h1>

<%= form_tag funcionarios_url, method: :get do %>
    <%= label_tag :q_cpf, "buscar por cpf" %>
    <%= search_field_tag :q_cpf %>
    <%= submit_tag "Buscar" %>
<% end %>

<table class="table">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cpf</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
    

  <tbody>
      <% if @funcionarios.blank?  %>
      <tr><td colspan=5>Não foi encontrado funcionario. <%= link_to "Ver todos", funcionarios_url %>
</td> </tr>
      <% else %>
        <% @funcionarios.each do |funcionario| %>
          <tr>
            <td><%= funcionario.nome %></td>
            <td><%= funcionario.cpf %></td>
            <td><%= link_to 'Show', funcionario %></td>
            <td><%= link_to 'Edit', edit_funcionario_path(funcionario) %></td>
            <td><%= link_to 'Destroy', funcionario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Funcionario', new_funcionario_path %>

app/views/funcionarios/new.html.erb
<h1>New funcionario</h1>

<%= render 'form' %>

<%= link_to 'Back', funcionarios_path %>

app/views/funcionarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @funcionario.nome %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @funcionario.cpf %>
</p>

<%= link_to 'Edit', edit_funcionario_path(@funcionario) %> |
<%= link_to 'Back', funcionarios_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Folha</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <nav class="navbar navbar-default" role="navigation">
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><%= link_to "Pagina Inicial", root_url %></li>
                <li><%= link_to "Cargos", cargos_url %></li>
                <li><%= link_to "Funcinarios", funcionarios_url %></li>
                <li><%= link_to "Vinculos", vinculos_url %></li>
            </ul>
        </div>
    </nav>
    
    <div class="container"> 
    <%= yield %>
    </div>

</body>
</html>

app/views/paginas/index.html.erb
<h1>seja bem vindo ao folha</h1>

app/views/vinculos/_form.html.erb
<%= form_for(@vinculo) do |f| %>
  <% if @vinculo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vinculo.errors.count, "error") %> prohibited this vinculo from being saved:</h2>

      <ul>
      <% @vinculo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :matricula %><br>
    <%= f.number_field :matricula %>
  </div>
  <div class="field">
    <%= f.label :dt_admissao %><br>
    <%= f.date_select :dt_admissao %>
  </div>
  <div class="field">
    <%= f.label :cargo_id %><br>
    <%= f.number_field :cargo_id %>
  </div>
  <div class="field">
    <%= f.label :funcionario_id %><br>
    <%= f.number_field :funcionario_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vinculos/edit.html.erb
<h1>Editing vinculo</h1>

<%= render 'form' %>

<%= link_to 'Show', @vinculo %> |
<%= link_to 'Back', vinculos_path %>

app/views/vinculos/index.html.erb
<h1>Listing vinculos</h1>

<table class="table">
  <thead>
    <tr>
      <th>Matricula</th>
      <th>Dt admissao</th>
      <th>Cargo</th>
      <th>Funcionario</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>  

  <tbody>
    <% @vinculos.each do |vinculo| %>
      <tr>
        <td><%= vinculo.matricula %></td>
        <td><%= vinculo.dt_admissao %></td>
        <td><%= vinculo.cargo_id %></td>
        <td><%= vinculo.funcionario_id %></td>
        <td><%= link_to 'Show', vinculo %></td>
        <td><%= link_to 'Edit', edit_vinculo_path(vinculo) %></td>
        <td><%= link_to 'Destroy', vinculo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vinculo', new_vinculo_path %>

app/views/vinculos/new.html.erb
<h1>New vinculo</h1>

<%= render 'form' %>

<%= link_to 'Back', vinculos_path %>

app/views/vinculos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Matricula:</strong>
  <%= @vinculo.matricula %>
</p>

<p>
  <strong>Dt admissao:</strong>
  <%= @vinculo.dt_admissao %>
</p>

<p>
  <strong>Cargo:</strong>
  <%= @vinculo.cargo_id %>
</p>

<p>
  <strong>Funcionario:</strong>
  <%= @vinculo.funcionario.cpf %>
</p>

<%= link_to 'Edit', edit_vinculo_path(@vinculo) %> |
<%= link_to 'Back', vinculos_path %>